name: Build NoCheatPlus
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build NoCheatPlus
        run: mvn clean package -P nonfree_build -P all
      - name: Upload NoCheatPlus
        uses: actions/upload-artifact@v3
        with:
          name: NoCheatPlus
          path: target/*.jar
